openapi: "3.0.0"
info:
  title: Tshirt Store API
  description: Make everything Okay.
  version: 1.1.0
  contact:
    email: ggwap099@gmail.com
    url: "https://junpak.dev"

# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: for localhost regular
#   - url: "https://localhost:4000/api/v1"
#     description: secure

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for localhost regular
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: httpd
        
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID 
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /homeDashboard:
    get:
      tags:
        - String
      summary: return lco data
      responses:
        200:
          description: success
          content: 
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error
